add-stochasticity + figure 5 and 6
BIO6032/2018_replication_hassell_1985 pull request #21
Opened 2018-03-30 16:49 UTC by DominiqueCaron

Mon essai d'ajouter de la stochasticité. J'ai fait le code pour les figures 5a-c et 6a-c.

2 choses
- J'ai réduit la stochasticité dans bien des cas, sinon les populations s'éteignaient et ça faisait crasher le modèle
- Je sais pas comment faire les figures 5d-f et 6d-f avec k-value

2018-03-30 17:09 UTC, vincelessard reviewed
Je sais pas si c'est prévu, mais dans le code du fichier functions.jl, tu as 2fois le @NT avec les paramètres (lignes 30 et 36)
Aussi, est-ce qu'il faudrait ajouter D_sd, a_sd, h_sd et c_sd dans les paramètres du NamedTupples?

2018-03-30 17:27 UTC, tpoisot requested changes

2018-03-30 17:27 UTC, tpoisot commented on code/figure4.jl
> +using NamedTuples
Il faudrait utiliser `Distributions`

~~~ julia
using Distributions
~~~

2018-03-30 17:27 UTC, tpoisot commented on code/functions.jl
> +        current_D=randn()*D_sd+D
Une fois que ça passera par `Distributions`, il faudra faire

~~~ julia
current_D = rand(Normal(p.D, p.D_sd))
# etc...
~~~

2018-03-30 17:27 UTC, tpoisot commented on code/functions.jl
> +function simulation(N::Float64, P::Float64; t::Int64=50, f=specialist_dyn, F=4.0, D=0.5, c=1.0, a=0.5, h=10.0, b=25.0, th=0.0, m=0.2, D_sd=0.0, a_sd=0.0, h_sd=0.0, c_sd=0.0)
:+1:

2018-03-30 17:27 UTC, tpoisot commented on code/functions.jl
> +        p = @NT(F=F, D=current_D, c=current_c, a=current_a, h=current_h, b=b, th=th, m=m)
Il faudrait utiliser un autre nom pour le tuple: `current_p`, ou `timestep_parameters`.

2018-03-30 17:29 UTC, vincelessard commented on code/functions.jl
> +        current_D=randn()*D_sd+D
On a déjà essayé et la fonction rand(Normal(mean, sd)) ne fonctionne pas avec un sd=0

2018-04-02 15:31 UTC, DominiqueCaron commented on code/functions.jl
> +        current_D=randn()*D_sd+D
en effet, en utilisant Distributions, il faudrait faire des boucle if(), sinon lorsque c'est non stochastique, la fonction ne fonctionne pas

2018-04-04 18:05 UTC, vincelessard approved these changes

2018-04-04 18:06 UTC, vincelessard approved these changes

2018-04-04 18:10 UTC, QileWu approved these changes

2018-04-05 13:47 UTC, merged